-- Create Transactions Table
create table transactions (
  id bigint generated by default as identity primary key,
  uuid uuid not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  amount numeric not null,
  type text not null check (type in ('income', 'expense')),
  category text not null,
  description text,
  date date not null,
  file_url text,
  user_id uuid references auth.users not null default auth.uid()
);

-- Set up Row Level Security (RLS)
alter table transactions enable row level security;

-- Policy: Users can only see their own transactions
create policy "Users can view their own transactions"
  on transactions for select
  using ( auth.uid() = user_id );

-- Policy: Users can insert their own transactions
create policy "Users can insert their own transactions"
  on transactions for insert
  with check ( auth.uid() = user_id );

-- Policy: Users can update their own transactions
create policy "Users can update their own transactions"
  on transactions for update
  using ( auth.uid() = user_id );

-- Policy: Users can delete their own transactions
create policy "Users can delete their own transactions"
  on transactions for delete
  using ( auth.uid() = user_id );
